# Generated by Django 6.0 on 2025-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_task_options_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Запланировано'), ('IN_PROGRESS', 'В процессе'), ('DONE', 'Завершено')], default='PLANNED', max_length=20),
        ),
    ]
