"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path

# ────────────────────────────────
# Пути проекта
# ────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# ────────────────────────────────
# Безопасность
# ────────────────────────────────
SECRET_KEY = 'django-insecure-REPLACE_THIS_WITH_YOUR_SECRET_KEY'
DEBUG = True
ALLOWED_HOSTS = []

# ────────────────────────────────
# Приложения
# ────────────────────────────────
INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
#
#     # REST API
#     'rest_framework',
#     'drf_yasg',
#
#     # Свои приложения
     'api'
]

# ────────────────────────────────
# Middleware
# ────────────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ────────────────────────────────
# URL конфигурация
# ────────────────────────────────
ROOT_URLCONF = 'config.urls'

# ────────────────────────────────
# Шаблоны
# ────────────────────────────────
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Папки с шаблонами проекта
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ────────────────────────────────
# База данных (SQLite)
# ────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ────────────────────────────────
# Валидация пароля
# ────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ────────────────────────────────
# Локализация
# ────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ────────────────────────────────
# Статические файлы (CSS, JS, картинки)
# ────────────────────────────────
STATIC_URL = '/static/'

# Папки, где Django ищет статику в режиме разработки
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Папка для собранной статики (для продакшена)
STATIC_ROOT = BASE_DIR / "staticfiles"

# ────────────────────────────────
# REST Framework (DRF)
# ────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# ────────────────────────────────
# Swagger / drf_yasg
# ────────────────────────────────
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': True,
    'SECURITY_DEFINITIONS': {
        'basic': {'type': 'basic'}
    },
}

# ────────────────────────────────
# Прочие настройки
# ────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
